name: Build and Deploy Subdirectory

on:
  push:
    branches:
      - main # メインブランチの名前に合わせて変更

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.jsのセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # 使用するNode.jsのバージョン

      - name: Convert README.md to index.html
        run: |
          pandoc README.md -f markdown -t html -o index.html

      # サブディレクトリに移動して依存関係をインストール
      - name: Install dependencies
        working-directory: ./run-senpai
        run: npm install

      # サブディレクトリでビルド
      - name: Build project
        working-directory: ./run-senpai
        run: npm run build

      - name: Debug Check build output
        run: ls -l

      - name: Archive artifact
        run: |
          mkdir -p $RUNNER_TEMP
          mkdir ./deploy
          mv ./images deploy/
          mv ./run-senpai/dist deploy/run-senpai
          mv ./nervous-breakdown deploy/
          mv ./edamame deploy/
          tar \
            --directory ./deploy \
            -cvf $RUNNER_TEMP/artifact.tar \
            .

      - name: Check archive
        run: ls -l $RUNNER_TEMP  # アーカイブ内容の確認

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: /home/runner/work/_temp/artifact.tar
          retention-days: 1

  deploy:
    needs: build-and-upload
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          preview: false